eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  flight-management:
    endpoints:
      endpoint:
        uri: http://flight-management/flight
  fare-management:
    endpoints:
      endpoint:
        uri: http://fare-management/fare 
  booking-management:
    endpoints:
      endpoint:
        uri: http://booking-management/booking
